CAMEL 2/src/module/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required

from module.views import ModuleIndexView, ModuleDashboardView, ModuleDetailsView, NewModule

app_name = 'module'
urlpatterns = [
    url(r'^$', ModuleIndexView.as_view(), name='module_index'),
    url(r'^(?P<pk>\M\w+)/$', ModuleDetailsView.as_view(), name="module_detail"),
    url(r"^(?P<module_pk>\w+)/", include("latexbook.urls", namespace="latexbook")),
    url(r'^Dashboard/$', login_required(ModuleDashboardView.as_view()), name='module_dashboard'),
    url(r'^NewModule/$', NewModule.as_view(), name="new_module"),
]

CAMEL 2/src/module/templates/module/book.html
{% extends "camelcore/base.html" %}
{% load static %}

{% block title %}
	Cardiff Maths e-Learning
{% endblock %}

{% block breadcrumbs %}
	&nbsp;
	{% if user.is_authenticated %}
		<a href="{% url 'user:user_home' user.pk %}">{{ user.username }}</a>
	{% else %}
		<a href="{% url 'camelcore.views.index' %}">home</a>
	{% endif %}
	<span> > </span> <a href="{% url 'module:module_index' %}">Modules</a>
{% endblock %}


{% block content-main %}
<div>
	<h1>{{ book }}</h1>
</div>

{% endblock %}

CAMEL 2/src/module/templates/module/module_detail.html
{% extends "camelcore/base.html" %}
{% load static %}

{% block title %}
	Cardiff Maths e-Learning
{% endblock %}

{% block breadcrumbs %}
	&nbsp;
	{% if user.is_authenticated %}
		<a href="{% url 'user:user_home' user.pk %}">{{ user.username }}</a>
	{% else %}
		<a href="{% url 'camelcore.views.index' %}">home</a>
	{% endif %}
	<span> > </span><a href="{% url 'module:module_index' %}">Modules</a>
	<span> > </span><a href="{% url 'module:module_detail' module.pk %}">Modules</a>
{% endblock %}

{% block content-main %}
<div>
	<h1>{{ module.code }}</h1>
	<p>The module title is {{ module.title }}</p>
</div>
{% endblock %}

CAMEL 2/src/module/templates/module/module_index.html
{% extends "camelcore/base.html" %}
{% load static %}

{% block title %}
	Cardiff Maths e-Learning
{% endblock %}


{% block content-main %}
<div>
	{% if modules|length > 0 %}
	<h1>Modules Available</h1>
		{% for mo in modules %}
			<!-- Test URL Provided -->
			<a href="/module/">{{ mo.code }} - {{ mo.title }}</a>
		{% endfor %}
	{% else %}
		<h1>No Modules Available</h1>
	{% endif %}
</div>

{% endblock %}